### PR TITLE
Fix vite

### PR DESCRIPTION
**Pull request by stringsam**
Added support for webpack next to vite.

Hot reload collides with webpack, we need to set 'mix_hot_proxy_url' => 'http://localhost' in app.php config.

### CODE REVIEW

**Comment by palypster** [comment]
Let's think about if this is a breaking change or not. Should we support both versions of Laravel (pre-vite and vite versions)?

Can you please also provide a PR for the update of the docs, how this should be used.

**Comment by timoransky** [comment]
@palypster I don't understand your question. As far as I understand, this PR makes possible to install Craftable with webpack alongside whatever one is uses on the frontend. So to answer `Should we support both versions of Laravel (pre-vite and vite versions)?` both of them are already supported in this PR. Or not?

**Comment by palypster** [comment]
I don't think so, because if you look closely on the PR, Samuel suppose there is no webpack.mix.js present in the project, thus install script creates it (previously it appended into it)

**Comment by stringsam** [comment]
We can check before installation whether webpack.js is present. If not, it will be created and build scripts in package.json will be changed to craftable-dev / craftable-prod. Otherwise, webpack will be only modified, and scripts can stay untouched. This way it won't be breaking change.

**Comment by palypster** [comment]
Okay, so let's sum it up. What we (probably) want to cover are these scenarios:
1) Installing Craftable on existing project, that has older Laravel that uses webpack
2) Installing Craftable on existing project, that has latest Laravel that uses vite and does not use webpack
3) Installing Craftable on existing project, that has latest Laravel that uses vite, but also use webpack for something else maybe (maybe vo FE)?
4) Installing new Craftable on Latest Laravel

I guess 2 and 4 are the same. What we need to solve is 1. Support for the 3 is nice-to-have, but not a must.

**Comment by stringsam** [comment]
I think that what I suggested covers all mentioned scenarios. The only minor issue is that in 3. point, creating build/prod scripts is unnecessary, but it shouldn't break anything.

**Review by timoransky — APPROVED** [review]

**Comment by erikgreasy** [comment]
New command `npm run craftable-dev` doesn't work as expected, because default package.json in Laravel contains `"type": "module"`. The fix for this could be to remove "type" from package.json completely?

**Pull request merged**
